# Generated by Django 4.1.7 on 2023-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberhub_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
