# Generated by Django 4.1.7 on 2023-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberhub_API', '0002_conference_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='publish_deadline',
            field=models.DateField(blank=True),
        ),
    ]
