# Generated by Django 4.1.7 on 2023-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberhub_API', '0003_alter_conference_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
